"""empty message

Revision ID: 16ade1c22ea3
Revises: None
Create Date: 2016-04-24 02:16:39.665000

"""

# revision identifiers, used by Alembic.
revision = '16ade1c22ea3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'fooditem', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fooditem', 'category', ['category_id'], ['id'])
    op.add_column(u'order', sa.Column('status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'order', 'status')
    op.drop_constraint(None, 'fooditem', type_='foreignkey')
    op.drop_column(u'fooditem', 'category_id')
    op.drop_table('category')
    ### end Alembic commands ###
